Add SMS custom status code
zenvia/zenvia-openapi-spec pull request #188
Opened 2022-03-24 21:04 UTC by rafamagalhas

Complementar os códigos de status retornado pelo conector de sms. Dessa forma o mesmo, além dos status HTTP, contemplará os códigos customizados que eram utilizados pela REST API.

- Adicionado uma listagem com os códigos de status customizados.

2022-03-24 22:09 UTC, rafael-org commented
Não acho uma boa colocar isso não, especialmente na sessão de status genérica, assim como não tem pro Whats.

2022-03-24 22:11 UTC, rafael-org commented
Se for pra ter detalhes por canal, acho que seria outra atividade, e a gente deveria levantar pra todos e deixar bem organizado em algum outro lugar (talvez em páginas separadas), mas desse jeito não acho uma boa não.

2022-03-24 22:12 UTC, rafael-org commented
Pois a ideia é focar nos status principais mesmo. Os detalhes são mais informativos.

2022-03-24 22:12 UTC, rafael-org commented
Se fossem importantes a gente mapeava.

2022-03-24 22:40 UTC, rafael-org commented
Resumindo, se fosse pra documentar, seria via modelagem desses status e não via texto. A documentação deveria ser só pra coisas que não é possível via modelagem, e isso é perfeitamente modelável!

2022-03-24 22:40 UTC, rafael-org requested changes
Então eu cancelaria esse PR.

2022-03-25 11:46 UTC, rafamagalhas commented
@rafael-org concordo contigo, podemos trocar uma ideia e trabalhar isso em um outro momento

2022-03-25 11:48 UTC, closed without merging