Two Factor Authentication
zenvia/zenvia-openapi-spec pull request #237
Opened 2022-11-03 12:13 UTC by isabelamn07

2022-11-07 19:20 UTC, alannaidon commented on spec/components/schemas/2fa/configuration/requests/website.ts
> +  description: 'Needded information to use this API two factor authentication service using a website or a mobile app',
Acho que ficaria melhor:
`Information needed to use this two factor authentication API service on a website or on a mobile app.`

2022-11-07 19:32 UTC, alannaidon commented on spec/tags/2fa.md
> +It's possible to create a variety of configurations of tokens that will be sended using two channels: SMS or E-mail.
só trocar o `sended` por `sent`

2022-11-07 20:37 UTC, victorshp requested changes
@isabelamn07 , só lembrando que os itens urgentes abaixo tem no seu comentário a palavra **VERIFICAR** para você poder usar no CTRL+F e achar mais facilmente.
Esses eu considero como erros que devem ser consertados antes do deploy. Os outros são erros de ortografia menos urgentes.

2022-11-07 20:37 UTC, victorshp commented on spec/paths/2fa/2fa-tokens@acions@verify.ts
> +  description: 'Verify a token',
**VERIFICAR**

Não seria **Send the code to the user**?

Como tem um recurso da API chamado "Resend the code to the user", se o objetivo é enviar o código pro usuário mesmo, o jeito que está escrito pode criar confusão

**+**
Se é realmente enviar o código pro usuário, tem que criar um novo schema pra esse recurso (recurso no sentido desse recurso CRUD específico da API).
Seria substiuir o `toCodeRef` (na L14 abaixo) por algo novo, pois a propriedade `code` desse recurso seria **code sent to the user** ao invés de **code sent by the user**
(https://github.com/zenvia/zenvia-openapi-spec/pull/237/files#diff-2874fdb3c8bbb35a7b0fd01a7356a853c4370ccd0e393e57c760a0de8892b938R17)

2022-11-07 20:37 UTC, victorshp commented on spec/components/schemas/2fa/token/requests/recipient.ts
> +      description: 'Code sended by the user',
**sent**
"sended" é gramaticamente incorreto

2022-11-07 20:37 UTC, victorshp commented on spec/components/schemas/2fa/token/responses/token.ts
> +      description: 'Location configured used',
**used** está redundante contextualmente e errado gramaticamente. Se tirar ele, fica correto.

2022-11-07 20:37 UTC, victorshp commented on spec/paths/2fa/2fa-cofigurations.ts
> +import { OperationObject, PathItemObject, ResponseObject } from 'openapi3-ts';
**VERIFICAR**

O nome do arquivo e, portanto, da rota está incorreto.
Na doc, o path para esse recurso aparece como **https://api.zenvia.com/v2/2fa-cofigurations**. Faltou o "n" para `configurations`.

2022-11-07 20:37 UTC, victorshp commented on spec/paths/2fa/2fa-tokens@acions@verify.ts
> +import { OperationObject, PathItemObject, ResponseObject } from 'openapi3-ts';
**VERIFICAR**

O nome do arquivo e, portanto, da rota está incorreto.
Na doc, o path para esse recurso aparece como **https://api.zenvia.com/v2/2fa-tokens/acions/verify**. Faltou o "t" para `actions`.

2022-11-07 22:43 UTC, isabelamn07 commented on spec/components/schemas/2fa/configuration/requests/website.ts
> +      readOnly: true,
Acredito que esteja certo, essa chave é gerado e devolvida com resposta, mas não deve ser enviada no payload

2022-11-08 02:45 UTC, victorshp commented on spec/components/schemas/2fa/token/requests/recipient.ts
> +      description: 'Code sended by the user',
Aqui ainda está incorreto, mas aprovei o MR

2022-11-08 02:45 UTC, victorshp approved these changes

2022-11-16 19:06 UTC, merged