[WHAT-2989] otp button
zenvia/zenvia-openapi-spec pull request #286
Opened 2023-05-24 12:43 UTC by felipedalcarobo

2023-05-24 17:03 UTC, guisteink approved these changes

2023-05-29 10:57 UTC, rafaelgpimenta requested changes

2023-05-29 10:57 UTC, rafaelgpimenta commented on spec/components/schemas/templates/components/index.ts
> +    otp: {
Campo body "required" não vai permitir a criação de templates de autenticação do whatsapp

2023-05-29 15:22 UTC, rafaelgpimenta approved these changes

2023-05-29 18:15 UTC, merged